name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: voidash/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ec702977fe05be27ab7b0b0b716e1616
          GIST_ID_SECOND: 4116b3a012f953fb9c4a1a5afa49d37f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
